# If this file is in a non-standard location, set the STARSHIP_CONFIG environment
# variable to its path: https://starship.rs/config/#config-file-location

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[os]
disabled = false

[os.symbols]
Debian = " "
Windows = " "

[git_status]
ahead = '${count}a'
behind = '${count}b'
conflicted = '${count}c'
deleted = '${count}d'
diverged = '${ahead_count}/${behind_count}D'
modified = '${count}m'
renamed = '${count}r'
staged = '${count}s'
stashed = '${count}S'
untracked = '${count}u'
up_to_date = '✓'
