# Integration tests for dotfiles! Has DevOps gone too far?

name: "Run setup scripts"

on:
  push:

jobs:
  run:
    name: Run setup scripts

    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            script: "debian.sh"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x ${{ matrix.script }}
          ./${{ matrix.script }}
